export const DefectEvidenceSchema = `query defectEvidence($defectId: String!) {
    defectEvidence(defectId: $defectId){
        summary
        remediation
        logs{
            timestamp
            message
            severity
            entity{
                name
                id
                typeName
            }
        }
        exceptions{
            timestamp
            message
            entity{
                name
                id
                typeName
            }
        }
        symptoms{
            id
            name
            displayName
            fromTime
            toTime
            indicator{
                name
            }
            entity{
                name
                id
                typeName
            }
            typeName
        }
        events{
            timestamp
            severity
            message
            entity{
                name
                id
                typeName
            }
        }
    }
}`;
