export const DefectConnectionQuery = `query defectConnection($defectFilter: DefectFilter, $groupRecurring: Boolean, $first: Int, $after: String, $last: Int, $before: String) {
    defectConnection(defectFilter: $defectFilter, groupRecurring: $groupRecurring, first: $first, after: $after, last: $last, before: $before){
        totalCount
        edges{
            node{
                id
                name
                entityId
                entity{
                    id
                    name
                    typeName
                    symptoms{
                        id
                        name
                        entityId
                        entityType
                        active
                        state
                        isPropagated
                        fromTime
                        toTime
                    }
                    events{
                        id
                        name
                        entityId
                        entityType
                        time
                        active
                    }
                    labels{
                        key
                        value
                    }
                    slos{
                        id
                        name
                        entityId
                        entityType
                        active
                        fromTime
                    }
                    severity
                }
                entityType
                symptoms{
                    id
                    name
                    entityId
                    entity{
                        id
                        name
                        typeName
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    entityType
                    active
                    state
                    isPropagated
                    fromTime
                    toTime
                }
                slos{
                    id
                    entity{
                        id
                        name
                        typeName
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    relatedEntity{
                        id
                        name
                        typeName
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    metrics{
                        id
                        attributes{
                            name
                            attrType
                            unit
                        }
                        indicators{
                            name
                        }
                        resources{
                            name
                        }
                    }
                    state
                }
                events{
                    id
                    name
                    entityId
                    entity{
                        id
                        name
                        typeName
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    entityType
                    time
                    active
                }
                fromTime
                toTime
                SLOAtRiskCount
                SLOTTL
                serviceCount
                remediated
                likelihood
                activeCount
                missingCount
                severity
                impacts{
                    id
                    name
                    entityId
                    entity{
                        id
                        name
                        typeName
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    entityType
                    active
                    state
                    isPropagated
                    fromTime
                    toTime
                }
            }
            cursor
        }
        pageInfo{
            hasNextPage
            hasPreviousPage
            startCursor
            endCursor
            totalCount
        }
    }
}`;
