export const EntityRelatedDefectsSchema = `query entityRelatedDefects($entityIds: [String!]!, $startTime: Time, $endTime: Time, $groupRecurring: Boolean) {
    entityRelatedDefects(entityIds: $entityIds, startTime: $startTime, endTime: $endTime, groupRecurring: $groupRecurring){
        entity{
            id
            name
            typeName
            symptoms{
                id
                name
                entityId
                entityType
                active
                state
                isPropagated
                fromTime
                toTime
                activeDefects{
                    id
                    name
                    entityId
                    entityType
                    slos{
                        id
                        metrics{
                            id
                            attributes{
                                name
                                attrType
                                unit
                            }
                            indicators{
                                name
                            }
                            resources{
                                name
                            }
                        }
                        state
                    }
                    events{
                        id
                        name
                        entityId
                        entityType
                        time
                        active
                    }
                    fromTime
                    toTime
                    SLOAtRiskCount
                    SLOTTL
                    serviceCount
                    remediated
                    likelihood
                    activeCount
                    missingCount
                    severity
                }
            }
            events{
                id
                name
                entityId
                entityType
                time
                active
                activeDefects{
                    id
                    name
                    entityId
                    entityType
                    symptoms{
                        id
                        name
                        entityId
                        entityType
                        active
                        state
                        isPropagated
                        fromTime
                        toTime
                    }
                    slos{
                        id
                        metrics{
                            id
                            attributes{
                                name
                                attrType
                                unit
                            }
                            indicators{
                                name
                            }
                            resources{
                                name
                            }
                        }
                        state
                    }
                    fromTime
                    toTime
                    SLOAtRiskCount
                    SLOTTL
                    serviceCount
                    remediated
                    likelihood
                    activeCount
                    missingCount
                    severity
                    impacts{
                        id
                        name
                        entityId
                        entityType
                        active
                        state
                        isPropagated
                        fromTime
                        toTime
                    }
                }
            }
            labels{
                key
                value
            }
            slos{
                id
                name
                entityId
                entityType
                active
                fromTime
            }
            defects{
                id
                name
                entityId
                entityType
                symptoms{
                    id
                    name
                    entityId
                    entityType
                    active
                    state
                    isPropagated
                    fromTime
                    toTime
                }
                slos{
                    id
                    metrics{
                        id
                        attributes{
                            name
                            attrType
                            unit
                        }
                        indicators{
                            name
                        }
                        resources{
                            name
                        }
                    }
                    state
                }
                events{
                    id
                    name
                    entityId
                    entityType
                    time
                    active
                }
                fromTime
                toTime
                SLOAtRiskCount
                SLOTTL
                serviceCount
                remediated
                likelihood
                activeCount
                missingCount
                severity
                impacts{
                    id
                    name
                    entityId
                    entityType
                    active
                    state
                    isPropagated
                    fromTime
                    toTime
                }
            }
            severity
        }
        relatedDefects{
            impactingDefects{
                id
                name
                entityId
                entity{
                    id
                    name
                    typeName
                    symptoms{
                        id
                        name
                        entityId
                        entityType
                        active
                        state
                        isPropagated
                        fromTime
                        toTime
                    }
                    events{
                        id
                        name
                        entityId
                        entityType
                        time
                        active
                    }
                    labels{
                        key
                        value
                    }
                    slos{
                        id
                        name
                        entityId
                        entityType
                        active
                        fromTime
                    }
                    severity
                }
                entityType
                symptoms{
                    id
                    name
                    entityId
                    entity{
                        id
                        name
                        typeName
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    entityType
                    active
                    state
                    isPropagated
                    fromTime
                    toTime
                }
                slos{
                    id
                    entity{
                        id
                        name
                        typeName
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    relatedEntity{
                        id
                        name
                        typeName
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    metrics{
                        id
                        attributes{
                            name
                            attrType
                            unit
                        }
                        indicators{
                            name
                        }
                        resources{
                            name
                        }
                    }
                    state
                }
                events{
                    id
                    name
                    entityId
                    entity{
                        id
                        name
                        typeName
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    entityType
                    time
                    active
                }
                fromTime
                toTime
                SLOAtRiskCount
                SLOTTL
                serviceCount
                remediated
                likelihood
                activeCount
                missingCount
                severity
                impacts{
                    id
                    name
                    entityId
                    entity{
                        id
                        name
                        typeName
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    entityType
                    active
                    state
                    isPropagated
                    fromTime
                    toTime
                }
            }
            aggregatingDefects{
                id
                name
                entityId
                entity{
                    id
                    name
                    typeName
                    symptoms{
                        id
                        name
                        entityId
                        entityType
                        active
                        state
                        isPropagated
                        fromTime
                        toTime
                    }
                    events{
                        id
                        name
                        entityId
                        entityType
                        time
                        active
                    }
                    labels{
                        key
                        value
                    }
                    slos{
                        id
                        name
                        entityId
                        entityType
                        active
                        fromTime
                    }
                    severity
                }
                entityType
                symptoms{
                    id
                    name
                    entityId
                    entity{
                        id
                        name
                        typeName
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    entityType
                    active
                    state
                    isPropagated
                    fromTime
                    toTime
                }
                slos{
                    id
                    entity{
                        id
                        name
                        typeName
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    relatedEntity{
                        id
                        name
                        typeName
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    metrics{
                        id
                        attributes{
                            name
                            attrType
                            unit
                        }
                        indicators{
                            name
                        }
                        resources{
                            name
                        }
                    }
                    state
                }
                events{
                    id
                    name
                    entityId
                    entity{
                        id
                        name
                        typeName
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    entityType
                    time
                    active
                }
                fromTime
                toTime
                SLOAtRiskCount
                SLOTTL
                serviceCount
                remediated
                likelihood
                activeCount
                missingCount
                severity
                impacts{
                    id
                    name
                    entityId
                    entity{
                        id
                        name
                        typeName
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    entityType
                    active
                    state
                    isPropagated
                    fromTime
                    toTime
                }
            }
            directDefects{
                id
                name
                entityId
                entity{
                    id
                    name
                    typeName
                    symptoms{
                        id
                        name
                        entityId
                        entityType
                        active
                        state
                        isPropagated
                        fromTime
                        toTime
                    }
                    events{
                        id
                        name
                        entityId
                        entityType
                        time
                        active
                    }
                    labels{
                        key
                        value
                    }
                    slos{
                        id
                        name
                        entityId
                        entityType
                        active
                        fromTime
                    }
                    severity
                }
                entityType
                symptoms{
                    id
                    name
                    entityId
                    entity{
                        id
                        name
                        typeName
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    entityType
                    active
                    state
                    isPropagated
                    fromTime
                    toTime
                }
                slos{
                    id
                    entity{
                        id
                        name
                        typeName
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    relatedEntity{
                        id
                        name
                        typeName
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    metrics{
                        id
                        attributes{
                            name
                            attrType
                            unit
                        }
                        indicators{
                            name
                        }
                        resources{
                            name
                        }
                    }
                    state
                }
                events{
                    id
                    name
                    entityId
                    entity{
                        id
                        name
                        typeName
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    entityType
                    time
                    active
                }
                fromTime
                toTime
                SLOAtRiskCount
                SLOTTL
                serviceCount
                remediated
                likelihood
                activeCount
                missingCount
                severity
                impacts{
                    id
                    name
                    entityId
                    entity{
                        id
                        name
                        typeName
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        labels{
                            key
                            value
                        }
                        slos{
                            id
                            name
                            entityId
                            entityType
                            active
                            fromTime
                        }
                        severity
                    }
                    entityType
                    active
                    state
                    isPropagated
                    fromTime
                    toTime
                }
            }
        }
    }
}`;
