export const EntityTypeSchema = `query entityTypeDefs($filter: EntityTypeDefFilter) {
    entityTypeDefs(filter: $filter){
        name
        defects{
            name
            displayName
            description{
                summary
                details
                remediationOptions{
                    title
                    description
                }
            }
            entityTypeName
            symptoms{
                name
                displayName
                entityTypeName
                impacts{
                    id
                    name
                    entityId
                    entity{
                        id
                        name
                        typeName
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                            activeDefects{
                                id
                                name
                                entityId
                                entityType
                                slos{
                                    id
                                    metrics{
                                        id
                                        attributes{
                                            name
                                            attrType
                                            unit
                                        }
                                        indicators{
                                            name
                                        }
                                        resources{
                                            name
                                        }
                                    }
                                    state
                                }
                                events{
                                    id
                                    name
                                    entityId
                                    entityType
                                    time
                                    active
                                }
                                fromTime
                                toTime
                                SLOAtRiskCount
                                SLOTTL
                                serviceCount
                                remediated
                                likelihood
                                activeCount
                                missingCount
                                severity
                            }
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                            activeDefects{
                                id
                                name
                                entityId
                                entityType
                                symptoms{
                                    id
                                    name
                                    entityId
                                    entityType
                                    active
                                    state
                                    isPropagated
                                    fromTime
                                    toTime
                                }
                                slos{
                                    id
                                    metrics{
                                        id
                                        attributes{
                                            name
                                            attrType
                                            unit
                                        }
                                        indicators{
                                            name
                                        }
                                        resources{
                                            name
                                        }
                                    }
                                    state
                                }
                                fromTime
                                toTime
                                SLOAtRiskCount
                                SLOTTL
                                serviceCount
                                remediated
                                likelihood
                                activeCount
                                missingCount
                                severity
                                impacts{
                                    id
                                    name
                                    entityId
                                    entityType
                                    active
                                    state
                                    isPropagated
                                    fromTime
                                    toTime
                                }
                            }
                        }
                        labels{
                            key
                            value
                        }
                        defects{
                            id
                            name
                            entityId
                            entityType
                            symptoms{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                            }
                            slos{
                                id
                                metrics{
                                    id
                                    attributes{
                                        name
                                        attrType
                                        unit
                                    }
                                    indicators{
                                        name
                                    }
                                    resources{
                                        name
                                    }
                                }
                                state
                            }
                            events{
                                id
                                name
                                entityId
                                entityType
                                time
                                active
                            }
                            fromTime
                            toTime
                            SLOAtRiskCount
                            SLOTTL
                            serviceCount
                            remediated
                            likelihood
                            activeCount
                            missingCount
                            severity
                            impacts{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                            }
                        }
                        severity
                    }
                    entityType
                    active
                    fromTime
                }
                contextAttributes
            }
            events{
                name
                entityTypeName
                impacts{
                    id
                    name
                    entityId
                    entity{
                        id
                        name
                        typeName
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                            activeDefects{
                                id
                                name
                                entityId
                                entityType
                                slos{
                                    id
                                    metrics{
                                        id
                                        attributes{
                                            name
                                            attrType
                                            unit
                                        }
                                        indicators{
                                            name
                                        }
                                        resources{
                                            name
                                        }
                                    }
                                    state
                                }
                                events{
                                    id
                                    name
                                    entityId
                                    entityType
                                    time
                                    active
                                }
                                fromTime
                                toTime
                                SLOAtRiskCount
                                SLOTTL
                                serviceCount
                                remediated
                                likelihood
                                activeCount
                                missingCount
                                severity
                            }
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                            activeDefects{
                                id
                                name
                                entityId
                                entityType
                                symptoms{
                                    id
                                    name
                                    entityId
                                    entityType
                                    active
                                    state
                                    isPropagated
                                    fromTime
                                    toTime
                                }
                                slos{
                                    id
                                    metrics{
                                        id
                                        attributes{
                                            name
                                            attrType
                                            unit
                                        }
                                        indicators{
                                            name
                                        }
                                        resources{
                                            name
                                        }
                                    }
                                    state
                                }
                                fromTime
                                toTime
                                SLOAtRiskCount
                                SLOTTL
                                serviceCount
                                remediated
                                likelihood
                                activeCount
                                missingCount
                                severity
                                impacts{
                                    id
                                    name
                                    entityId
                                    entityType
                                    active
                                    state
                                    isPropagated
                                    fromTime
                                    toTime
                                }
                            }
                        }
                        labels{
                            key
                            value
                        }
                        defects{
                            id
                            name
                            entityId
                            entityType
                            symptoms{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                            }
                            slos{
                                id
                                metrics{
                                    id
                                    attributes{
                                        name
                                        attrType
                                        unit
                                    }
                                    indicators{
                                        name
                                    }
                                    resources{
                                        name
                                    }
                                }
                                state
                            }
                            events{
                                id
                                name
                                entityId
                                entityType
                                time
                                active
                            }
                            fromTime
                            toTime
                            SLOAtRiskCount
                            SLOTTL
                            serviceCount
                            remediated
                            likelihood
                            activeCount
                            missingCount
                            severity
                            impacts{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                            }
                        }
                        severity
                    }
                    entityType
                    active
                    fromTime
                }
            }
            contextAttributes
            contextIndicators
        }
        attributes{
            name
            type
            unit
            description
        }
        symptoms{
            name
            displayName
            entityTypeName
            impacts{
                id
                name
                entityId
                entity{
                    id
                    name
                    typeName
                    symptoms{
                        id
                        name
                        entityId
                        entityType
                        active
                        state
                        isPropagated
                        fromTime
                        toTime
                        activeDefects{
                            id
                            name
                            entityId
                            entityType
                            slos{
                                id
                                metrics{
                                    id
                                    attributes{
                                        name
                                        attrType
                                        unit
                                    }
                                    indicators{
                                        name
                                    }
                                    resources{
                                        name
                                    }
                                }
                                state
                            }
                            events{
                                id
                                name
                                entityId
                                entityType
                                time
                                active
                            }
                            fromTime
                            toTime
                            SLOAtRiskCount
                            SLOTTL
                            serviceCount
                            remediated
                            likelihood
                            activeCount
                            missingCount
                            severity
                        }
                    }
                    events{
                        id
                        name
                        entityId
                        entityType
                        time
                        active
                        activeDefects{
                            id
                            name
                            entityId
                            entityType
                            symptoms{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                            }
                            slos{
                                id
                                metrics{
                                    id
                                    attributes{
                                        name
                                        attrType
                                        unit
                                    }
                                    indicators{
                                        name
                                    }
                                    resources{
                                        name
                                    }
                                }
                                state
                            }
                            fromTime
                            toTime
                            SLOAtRiskCount
                            SLOTTL
                            serviceCount
                            remediated
                            likelihood
                            activeCount
                            missingCount
                            severity
                            impacts{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                            }
                        }
                    }
                    labels{
                        key
                        value
                    }
                    defects{
                        id
                        name
                        entityId
                        entityType
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        slos{
                            id
                            metrics{
                                id
                                attributes{
                                    name
                                    attrType
                                    unit
                                }
                                indicators{
                                    name
                                }
                                resources{
                                    name
                                }
                            }
                            state
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        fromTime
                        toTime
                        SLOAtRiskCount
                        SLOTTL
                        serviceCount
                        remediated
                        likelihood
                        activeCount
                        missingCount
                        severity
                        impacts{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                    }
                    severity
                }
                entityType
                active
                fromTime
            }
            contextAttributes
        }
        events{
            name
            entityTypeName
            impacts{
                id
                name
                entityId
                entity{
                    id
                    name
                    typeName
                    symptoms{
                        id
                        name
                        entityId
                        entityType
                        active
                        state
                        isPropagated
                        fromTime
                        toTime
                        activeDefects{
                            id
                            name
                            entityId
                            entityType
                            slos{
                                id
                                metrics{
                                    id
                                    attributes{
                                        name
                                        attrType
                                        unit
                                    }
                                    indicators{
                                        name
                                    }
                                    resources{
                                        name
                                    }
                                }
                                state
                            }
                            events{
                                id
                                name
                                entityId
                                entityType
                                time
                                active
                            }
                            fromTime
                            toTime
                            SLOAtRiskCount
                            SLOTTL
                            serviceCount
                            remediated
                            likelihood
                            activeCount
                            missingCount
                            severity
                        }
                    }
                    events{
                        id
                        name
                        entityId
                        entityType
                        time
                        active
                        activeDefects{
                            id
                            name
                            entityId
                            entityType
                            symptoms{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                            }
                            slos{
                                id
                                metrics{
                                    id
                                    attributes{
                                        name
                                        attrType
                                        unit
                                    }
                                    indicators{
                                        name
                                    }
                                    resources{
                                        name
                                    }
                                }
                                state
                            }
                            fromTime
                            toTime
                            SLOAtRiskCount
                            SLOTTL
                            serviceCount
                            remediated
                            likelihood
                            activeCount
                            missingCount
                            severity
                            impacts{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                            }
                        }
                    }
                    labels{
                        key
                        value
                    }
                    defects{
                        id
                        name
                        entityId
                        entityType
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        slos{
                            id
                            metrics{
                                id
                                attributes{
                                    name
                                    attrType
                                    unit
                                }
                                indicators{
                                    name
                                }
                                resources{
                                    name
                                }
                            }
                            state
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        fromTime
                        toTime
                        SLOAtRiskCount
                        SLOTTL
                        serviceCount
                        remediated
                        likelihood
                        activeCount
                        missingCount
                        severity
                        impacts{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                    }
                    severity
                }
                entityType
                active
                fromTime
            }
        }
        relations{
            name
        }
        resources{
            name
            type
            defects{
                name
                displayName
                description{
                    summary
                    details
                    remediationOptions{
                        title
                        description
                    }
                }
                entityTypeName
                symptoms{
                    name
                    displayName
                    entityTypeName
                    impacts{
                        id
                        name
                        entityId
                        entity{
                            id
                            name
                            typeName
                            symptoms{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                                activeDefects{
                                    id
                                    name
                                    entityId
                                    entityType
                                    slos{
                                        id
                                        metrics{
                                            id
                                            attributes{
                                                name
                                                attrType
                                                unit
                                            }
                                            indicators{
                                                name
                                            }
                                            resources{
                                                name
                                            }
                                        }
                                        state
                                    }
                                    events{
                                        id
                                        name
                                        entityId
                                        entityType
                                        time
                                        active
                                    }
                                    fromTime
                                    toTime
                                    SLOAtRiskCount
                                    SLOTTL
                                    serviceCount
                                    remediated
                                    likelihood
                                    activeCount
                                    missingCount
                                    severity
                                }
                            }
                            events{
                                id
                                name
                                entityId
                                entityType
                                time
                                active
                                activeDefects{
                                    id
                                    name
                                    entityId
                                    entityType
                                    symptoms{
                                        id
                                        name
                                        entityId
                                        entityType
                                        active
                                        state
                                        isPropagated
                                        fromTime
                                        toTime
                                    }
                                    slos{
                                        id
                                        metrics{
                                            id
                                            attributes{
                                                name
                                                attrType
                                                unit
                                            }
                                            indicators{
                                                name
                                            }
                                            resources{
                                                name
                                            }
                                        }
                                        state
                                    }
                                    fromTime
                                    toTime
                                    SLOAtRiskCount
                                    SLOTTL
                                    serviceCount
                                    remediated
                                    likelihood
                                    activeCount
                                    missingCount
                                    severity
                                    impacts{
                                        id
                                        name
                                        entityId
                                        entityType
                                        active
                                        state
                                        isPropagated
                                        fromTime
                                        toTime
                                    }
                                }
                            }
                            labels{
                                key
                                value
                            }
                            defects{
                                id
                                name
                                entityId
                                entityType
                                symptoms{
                                    id
                                    name
                                    entityId
                                    entityType
                                    active
                                    state
                                    isPropagated
                                    fromTime
                                    toTime
                                }
                                slos{
                                    id
                                    metrics{
                                        id
                                        attributes{
                                            name
                                            attrType
                                            unit
                                        }
                                        indicators{
                                            name
                                        }
                                        resources{
                                            name
                                        }
                                    }
                                    state
                                }
                                events{
                                    id
                                    name
                                    entityId
                                    entityType
                                    time
                                    active
                                }
                                fromTime
                                toTime
                                SLOAtRiskCount
                                SLOTTL
                                serviceCount
                                remediated
                                likelihood
                                activeCount
                                missingCount
                                severity
                                impacts{
                                    id
                                    name
                                    entityId
                                    entityType
                                    active
                                    state
                                    isPropagated
                                    fromTime
                                    toTime
                                }
                            }
                            severity
                        }
                        entityType
                        active
                        fromTime
                    }
                    contextAttributes
                }
                events{
                    name
                    entityTypeName
                    impacts{
                        id
                        name
                        entityId
                        entity{
                            id
                            name
                            typeName
                            symptoms{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                                activeDefects{
                                    id
                                    name
                                    entityId
                                    entityType
                                    slos{
                                        id
                                        metrics{
                                            id
                                            attributes{
                                                name
                                                attrType
                                                unit
                                            }
                                            indicators{
                                                name
                                            }
                                            resources{
                                                name
                                            }
                                        }
                                        state
                                    }
                                    events{
                                        id
                                        name
                                        entityId
                                        entityType
                                        time
                                        active
                                    }
                                    fromTime
                                    toTime
                                    SLOAtRiskCount
                                    SLOTTL
                                    serviceCount
                                    remediated
                                    likelihood
                                    activeCount
                                    missingCount
                                    severity
                                }
                            }
                            events{
                                id
                                name
                                entityId
                                entityType
                                time
                                active
                                activeDefects{
                                    id
                                    name
                                    entityId
                                    entityType
                                    symptoms{
                                        id
                                        name
                                        entityId
                                        entityType
                                        active
                                        state
                                        isPropagated
                                        fromTime
                                        toTime
                                    }
                                    slos{
                                        id
                                        metrics{
                                            id
                                            attributes{
                                                name
                                                attrType
                                                unit
                                            }
                                            indicators{
                                                name
                                            }
                                            resources{
                                                name
                                            }
                                        }
                                        state
                                    }
                                    fromTime
                                    toTime
                                    SLOAtRiskCount
                                    SLOTTL
                                    serviceCount
                                    remediated
                                    likelihood
                                    activeCount
                                    missingCount
                                    severity
                                    impacts{
                                        id
                                        name
                                        entityId
                                        entityType
                                        active
                                        state
                                        isPropagated
                                        fromTime
                                        toTime
                                    }
                                }
                            }
                            labels{
                                key
                                value
                            }
                            defects{
                                id
                                name
                                entityId
                                entityType
                                symptoms{
                                    id
                                    name
                                    entityId
                                    entityType
                                    active
                                    state
                                    isPropagated
                                    fromTime
                                    toTime
                                }
                                slos{
                                    id
                                    metrics{
                                        id
                                        attributes{
                                            name
                                            attrType
                                            unit
                                        }
                                        indicators{
                                            name
                                        }
                                        resources{
                                            name
                                        }
                                    }
                                    state
                                }
                                events{
                                    id
                                    name
                                    entityId
                                    entityType
                                    time
                                    active
                                }
                                fromTime
                                toTime
                                SLOAtRiskCount
                                SLOTTL
                                serviceCount
                                remediated
                                likelihood
                                activeCount
                                missingCount
                                severity
                                impacts{
                                    id
                                    name
                                    entityId
                                    entityType
                                    active
                                    state
                                    isPropagated
                                    fromTime
                                    toTime
                                }
                            }
                            severity
                        }
                        entityType
                        active
                        fromTime
                    }
                }
                contextAttributes
                contextIndicators
            }
            attributes{
                name
                type
                unit
                description
            }
            symptoms{
                name
                displayName
                entityTypeName
                impacts{
                    id
                    name
                    entityId
                    entity{
                        id
                        name
                        typeName
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                            activeDefects{
                                id
                                name
                                entityId
                                entityType
                                slos{
                                    id
                                    metrics{
                                        id
                                        attributes{
                                            name
                                            attrType
                                            unit
                                        }
                                        indicators{
                                            name
                                        }
                                        resources{
                                            name
                                        }
                                    }
                                    state
                                }
                                events{
                                    id
                                    name
                                    entityId
                                    entityType
                                    time
                                    active
                                }
                                fromTime
                                toTime
                                SLOAtRiskCount
                                SLOTTL
                                serviceCount
                                remediated
                                likelihood
                                activeCount
                                missingCount
                                severity
                            }
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                            activeDefects{
                                id
                                name
                                entityId
                                entityType
                                symptoms{
                                    id
                                    name
                                    entityId
                                    entityType
                                    active
                                    state
                                    isPropagated
                                    fromTime
                                    toTime
                                }
                                slos{
                                    id
                                    metrics{
                                        id
                                        attributes{
                                            name
                                            attrType
                                            unit
                                        }
                                        indicators{
                                            name
                                        }
                                        resources{
                                            name
                                        }
                                    }
                                    state
                                }
                                fromTime
                                toTime
                                SLOAtRiskCount
                                SLOTTL
                                serviceCount
                                remediated
                                likelihood
                                activeCount
                                missingCount
                                severity
                                impacts{
                                    id
                                    name
                                    entityId
                                    entityType
                                    active
                                    state
                                    isPropagated
                                    fromTime
                                    toTime
                                }
                            }
                        }
                        labels{
                            key
                            value
                        }
                        defects{
                            id
                            name
                            entityId
                            entityType
                            symptoms{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                            }
                            slos{
                                id
                                metrics{
                                    id
                                    attributes{
                                        name
                                        attrType
                                        unit
                                    }
                                    indicators{
                                        name
                                    }
                                    resources{
                                        name
                                    }
                                }
                                state
                            }
                            events{
                                id
                                name
                                entityId
                                entityType
                                time
                                active
                            }
                            fromTime
                            toTime
                            SLOAtRiskCount
                            SLOTTL
                            serviceCount
                            remediated
                            likelihood
                            activeCount
                            missingCount
                            severity
                            impacts{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                            }
                        }
                        severity
                    }
                    entityType
                    active
                    fromTime
                }
                contextAttributes
            }
        }
        indicators{
            name
            type
            description
            attributes{
                name
                type
                unit
                description
            }
            symptoms{
                name
                displayName
                entityTypeName
                impacts{
                    id
                    name
                    entityId
                    entity{
                        id
                        name
                        typeName
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                            activeDefects{
                                id
                                name
                                entityId
                                entityType
                                slos{
                                    id
                                    metrics{
                                        id
                                        attributes{
                                            name
                                            attrType
                                            unit
                                        }
                                        indicators{
                                            name
                                        }
                                        resources{
                                            name
                                        }
                                    }
                                    state
                                }
                                events{
                                    id
                                    name
                                    entityId
                                    entityType
                                    time
                                    active
                                }
                                fromTime
                                toTime
                                SLOAtRiskCount
                                SLOTTL
                                serviceCount
                                remediated
                                likelihood
                                activeCount
                                missingCount
                                severity
                            }
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                            activeDefects{
                                id
                                name
                                entityId
                                entityType
                                symptoms{
                                    id
                                    name
                                    entityId
                                    entityType
                                    active
                                    state
                                    isPropagated
                                    fromTime
                                    toTime
                                }
                                slos{
                                    id
                                    metrics{
                                        id
                                        attributes{
                                            name
                                            attrType
                                            unit
                                        }
                                        indicators{
                                            name
                                        }
                                        resources{
                                            name
                                        }
                                    }
                                    state
                                }
                                fromTime
                                toTime
                                SLOAtRiskCount
                                SLOTTL
                                serviceCount
                                remediated
                                likelihood
                                activeCount
                                missingCount
                                severity
                                impacts{
                                    id
                                    name
                                    entityId
                                    entityType
                                    active
                                    state
                                    isPropagated
                                    fromTime
                                    toTime
                                }
                            }
                        }
                        labels{
                            key
                            value
                        }
                        defects{
                            id
                            name
                            entityId
                            entityType
                            symptoms{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                            }
                            slos{
                                id
                                metrics{
                                    id
                                    attributes{
                                        name
                                        attrType
                                        unit
                                    }
                                    indicators{
                                        name
                                    }
                                    resources{
                                        name
                                    }
                                }
                                state
                            }
                            events{
                                id
                                name
                                entityId
                                entityType
                                time
                                active
                            }
                            fromTime
                            toTime
                            SLOAtRiskCount
                            SLOTTL
                            serviceCount
                            remediated
                            likelihood
                            activeCount
                            missingCount
                            severity
                            impacts{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                            }
                        }
                        severity
                    }
                    entityType
                    active
                    fromTime
                }
                contextAttributes
            }
            contextAttributes
        }
        contextAttributes
    }
}`
