export const EntityConnectionSchema = `query entityConnection($entityFilter: EntityFilter, $first: Int, $after: String, $last: Int, $before: String) {
    entityConnection(entityFilter: $entityFilter, first: $first, after: $after, last: $last, before: $before){
        totalCount
        edges{
            node{
                id
                name
                typeName
                symptoms{
                    id
                    name
                    entityId
                    entityType
                    active
                    state
                    isPropagated
                    fromTime
                    toTime
                    activeDefects{
                        id
                        name
                        entityId
                        entityType
                        slos{
                            id
                            metrics{
                                id
                                attributes{
                                    name
                                    attrType
                                    unit
                                }
                                indicators{
                                    name
                                }
                                resources{
                                    name
                                }
                            }
                            state
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        fromTime
                        toTime
                        SLOAtRiskCount
                        SLOTTL
                        serviceCount
                        remediated
                        likelihood
                        activeCount
                        missingCount
                        severity
                    }
                }
                events{
                    id
                    name
                    entityId
                    entityType
                    time
                    active
                    activeDefects{
                        id
                        name
                        entityId
                        entityType
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        slos{
                            id
                            metrics{
                                id
                                attributes{
                                    name
                                    attrType
                                    unit
                                }
                                indicators{
                                    name
                                }
                                resources{
                                    name
                                }
                            }
                            state
                        }
                        fromTime
                        toTime
                        SLOAtRiskCount
                        SLOTTL
                        serviceCount
                        remediated
                        likelihood
                        activeCount
                        missingCount
                        severity
                        impacts{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                    }
                }
                labels{
                    key
                    value
                }
                slos{
                    id
                    name
                    entityId
                    entityType
                    active
                    fromTime
                }
                defects{
                    id
                    name
                    entityId
                    entityType
                    symptoms{
                        id
                        name
                        entityId
                        entityType
                        active
                        state
                        isPropagated
                        fromTime
                        toTime
                    }
                    slos{
                        id
                        metrics{
                            id
                            attributes{
                                name
                                attrType
                                unit
                            }
                            indicators{
                                name
                            }
                            resources{
                                name
                            }
                        }
                        state
                    }
                    events{
                        id
                        name
                        entityId
                        entityType
                        time
                        active
                    }
                    fromTime
                    toTime
                    SLOAtRiskCount
                    SLOTTL
                    serviceCount
                    remediated
                    likelihood
                    activeCount
                    missingCount
                    severity
                    impacts{
                        id
                        name
                        entityId
                        entityType
                        active
                        state
                        isPropagated
                        fromTime
                        toTime
                    }
                }
                severity
            }
            cursor
        }
        pageInfo{
            hasNextPage
            hasPreviousPage
            startCursor
            endCursor
            totalCount
        }
    }
}`;
