export const SloConnectionSchema = `query sloConnection($filter: SloFilter, $first: Int, $after: String, $last: Int, $before: String) {
    sloConnection(filter: $filter, first: $first, after: $after, last: $last, before: $before){
        totalCount
        edges{
            node{
                id
                entity{
                    id
                    name
                    typeName
                    symptoms{
                        id
                        name
                        entityId
                        entityType
                        active
                        state
                        isPropagated
                        fromTime
                        toTime
                        activeDefects{
                            id
                            name
                            entityId
                            entityType
                            events{
                                id
                                name
                                entityId
                                entityType
                                time
                                active
                            }
                            fromTime
                            toTime
                            SLOAtRiskCount
                            SLOTTL
                            serviceCount
                            remediated
                            likelihood
                            activeCount
                            missingCount
                            severity
                        }
                    }
                    events{
                        id
                        name
                        entityId
                        entityType
                        time
                        active
                        activeDefects{
                            id
                            name
                            entityId
                            entityType
                            symptoms{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                            }
                            fromTime
                            toTime
                            SLOAtRiskCount
                            SLOTTL
                            serviceCount
                            remediated
                            likelihood
                            activeCount
                            missingCount
                            severity
                            impacts{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                            }
                        }
                    }
                    labels{
                        key
                        value
                    }
                    slos{
                        id
                        name
                        entityId
                        entityType
                        active
                        fromTime
                    }
                    defects{
                        id
                        name
                        entityId
                        entityType
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        fromTime
                        toTime
                        SLOAtRiskCount
                        SLOTTL
                        serviceCount
                        remediated
                        likelihood
                        activeCount
                        missingCount
                        severity
                        impacts{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                    }
                    severity
                }
                relatedEntity{
                    id
                    name
                    typeName
                    symptoms{
                        id
                        name
                        entityId
                        entityType
                        active
                        state
                        isPropagated
                        fromTime
                        toTime
                        activeDefects{
                            id
                            name
                            entityId
                            entityType
                            events{
                                id
                                name
                                entityId
                                entityType
                                time
                                active
                            }
                            fromTime
                            toTime
                            SLOAtRiskCount
                            SLOTTL
                            serviceCount
                            remediated
                            likelihood
                            activeCount
                            missingCount
                            severity
                        }
                    }
                    events{
                        id
                        name
                        entityId
                        entityType
                        time
                        active
                        activeDefects{
                            id
                            name
                            entityId
                            entityType
                            symptoms{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                            }
                            fromTime
                            toTime
                            SLOAtRiskCount
                            SLOTTL
                            serviceCount
                            remediated
                            likelihood
                            activeCount
                            missingCount
                            severity
                            impacts{
                                id
                                name
                                entityId
                                entityType
                                active
                                state
                                isPropagated
                                fromTime
                                toTime
                            }
                        }
                    }
                    labels{
                        key
                        value
                    }
                    slos{
                        id
                        name
                        entityId
                        entityType
                        active
                        fromTime
                    }
                    defects{
                        id
                        name
                        entityId
                        entityType
                        symptoms{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                        events{
                            id
                            name
                            entityId
                            entityType
                            time
                            active
                        }
                        fromTime
                        toTime
                        SLOAtRiskCount
                        SLOTTL
                        serviceCount
                        remediated
                        likelihood
                        activeCount
                        missingCount
                        severity
                        impacts{
                            id
                            name
                            entityId
                            entityType
                            active
                            state
                            isPropagated
                            fromTime
                            toTime
                        }
                    }
                    severity
                }
                metrics{
                    id
                    attributes{
                        name
                        ... on StringAttribute {
                            stringValue: value
                            __typename
                        }
                        ... on BooleanAttribute {
                            booleanValue: value
                            __typename
                        }
                        ... on FloatAttribute {
                            floatValue: value
                            __typename
                        }
                        ... on IntAttribute {
                            intValue: value
                            __typename
                        }
                        ... on MetricAttribute {
                            metricValue: value {
                                values {
                                    timestamp
                                    value
                                    __typename
                                }
                                __typename
                            }
                            __typename
                        }
                        ... on HistogramAttribute {
                            histogramSum: sum {
                                values {
                                    timestamp
                                    value
                                    __typename
                                }
                                __typename
                            }
                            histogramCount: count {
                                values {
                                    timestamp
                                    value
                                    __typename
                                }
                                __typename
                            }
                            histogramBuckets: buckets {
                                upperBound
                                values {
                                    values {
                                        timestamp
                                        value
                                        __typename
                                    }
                                    __typename
                                }
                                __typename
                            }
                            __typename
                        }
                        ... on TableAttribute {
                            columns {
                                name
                                columnType
                                contentType
                                unit
                                __typename
                            }
                            rows {
                                values {
                                    intValue
                                    floatValue
                                    boolValue
                                    stringValue
                                    __typename
                                }
                                __typename
                            }
                            __typename
                        }
                    }
                    indicators{
                        name
                    }
                    resources{
                        name
                    }
                }
                state
            }
            cursor
        }
        pageInfo{
            hasNextPage
            hasPreviousPage
            startCursor
            endCursor
            totalCount
        }
    }
}`;