// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqmdl

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type Attribute interface {
	IsAttribute()
	GetName() string
	GetAttrType() AttributeType
	GetUnit() string
}

type Connection interface {
	IsConnection()
	GetTotalCount() int
	GetEdges() []Edge
	GetPageInfo() *PageInfo
}

type Edge interface {
	IsEdge()
	GetCursor() string
	GetNode() Node
}

type IndicatorData interface {
	IsIndicatorData()
	GetName() string
}

type Node interface {
	IsNode()
	GetID() string
}

type ResourceData interface {
	IsResourceData()
	GetName() string
}

type ADGEdge struct {
	FromNode *ConstraintResource `json:"fromNode,omitempty"`
	ToNode   *ConstraintResource `json:"toNode,omitempty"`
}

type ADGGraphEdge struct {
	FromNode *ADGGraphNode `json:"fromNode,omitempty"`
	ToNode   *ADGGraphNode `json:"toNode,omitempty"`
	EdgeType string        `json:"edgeType"`
}

type ADGGraphNode struct {
	Entity           *Entity               `json:"entity"`
	RelatedResources []*ConstraintResource `json:"relatedResources"`
	ChangedResources []*ConstraintResource `json:"changedResources"`
}

type ADGNode struct {
	Node             *ConstraintResource   `json:"node,omitempty"`
	RelatedResources []*ConstraintResource `json:"relatedResources"`
}

type Action struct {
	ID                string  `json:"id"`
	Type              string  `json:"type"`
	EntityID          string  `json:"entityId"`
	Entity            *Entity `json:"entity"`
	DefectID          string  `json:"defectId"`
	Defect            *Defect `json:"defect"`
	Description       string  `json:"description"`
	ResourceType      string  `json:"resourceType"`
	ResourceAttribute string  `json:"resourceAttribute"`
	ResourceValue     float64 `json:"resourceValue"`
	ExecutionStatus   string  `json:"executionStatus"`
	Executable        bool    `json:"executable"`
	Time              string  `json:"time"`
}

type Agent struct {
	ID                 string                    `json:"id"`
	Hostname           string                    `json:"hostname"`
	LastSeen           string                    `json:"lastSeen"`
	KernelVersion      *string                   `json:"kernelVersion,omitempty"`
	KernelRelease      *string                   `json:"kernelRelease,omitempty"`
	BuildVersion       *string                   `json:"buildVersion,omitempty"`
	ClusterName        *string                   `json:"clusterName,omitempty"`
	ConfiguredScrapers []*AgentConfiguredScraper `json:"configuredScrapers,omitempty"`
	DiscoveredScrapers []*AgentDiscoveredScraper `json:"discoveredScrapers,omitempty"`
}

type AgentConfiguredScraper struct {
	Name                     string  `json:"name"`
	Type                     string  `json:"type"`
	InitializationSuccessful bool    `json:"initializationSuccessful"`
	InitializationError      *string `json:"initializationError,omitempty"`
}

type AgentCount struct {
	RepositoryID string `json:"repositoryId"`
	Count        int    `json:"count"`
}

type AgentDiscoveredScraper struct {
	Type string `json:"type"`
}

type AttributeDef struct {
	Name        string  `json:"name"`
	Type        string  `json:"type"`
	Unit        *string `json:"unit,omitempty"`
	Description string  `json:"description"`
}

type AttributeQuery struct {
	Start       time.Time               `json:"start"`
	End         *time.Time              `json:"end,omitempty"`
	StepMinutes *int                    `json:"stepMinutes,omitempty"`
	Entities    []*EntityAttributeQuery `json:"entities"`
}

type BooleanAttribute struct {
	Name     string        `json:"name"`
	AttrType AttributeType `json:"attrType"`
	Value    bool          `json:"value"`
	Unit     string        `json:"unit"`
}

func (BooleanAttribute) IsAttribute()                    {}
func (this BooleanAttribute) GetName() string            { return this.Name }
func (this BooleanAttribute) GetAttrType() AttributeType { return this.AttrType }
func (this BooleanAttribute) GetUnit() string            { return this.Unit }

type Bucket struct {
	UpperBound float64 `json:"upperBound"`
	Values     *Metric `json:"values"`
}

type CausalityEdge struct {
	ID            string         `json:"id"`
	FromCausality *CausalityNode `json:"fromCausality"`
	ToCausality   *CausalityNode `json:"toCausality"`
	Probability   float64        `json:"probability"`
}

func (CausalityEdge) IsNode()            {}
func (this CausalityEdge) GetID() string { return this.ID }

type CausalityEdgeConnection struct {
	TotalCount int                  `json:"totalCount"`
	Edges      []*CausalityEdgeEdge `json:"edges"`
	PageInfo   *PageInfo            `json:"pageInfo,omitempty"`
}

func (CausalityEdgeConnection) IsConnection()           {}
func (this CausalityEdgeConnection) GetTotalCount() int { return this.TotalCount }
func (this CausalityEdgeConnection) GetEdges() []Edge {
	if this.Edges == nil {
		return nil
	}
	interfaceSlice := make([]Edge, 0, len(this.Edges))
	for _, concrete := range this.Edges {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this CausalityEdgeConnection) GetPageInfo() *PageInfo { return this.PageInfo }

type CausalityEdgeEdge struct {
	Node   *CausalityEdge `json:"node"`
	Cursor string         `json:"cursor"`
}

func (CausalityEdgeEdge) IsEdge()                {}
func (this CausalityEdgeEdge) GetCursor() string { return this.Cursor }
func (this CausalityEdgeEdge) GetNode() Node     { return *this.Node }

type CausalityNode struct {
	Type    string   `json:"type"`
	Symptom *Symptom `json:"symptom,omitempty"`
	Event   *Event   `json:"event,omitempty"`
	Slo     *Slo     `json:"slo,omitempty"`
	Defect  *Defect  `json:"defect,omitempty"`
}

type CodebookManifestationInput struct {
	EntityID          string `json:"entityId"`
	ManifestationName string `json:"manifestationName"`
	CausalityType     string `json:"causalityType"`
}

type ConstraintAnalysisConnection struct {
	TotalCount int                       `json:"totalCount"`
	Edges      []*ConstraintAnalysisEdge `json:"edges"`
	PageInfo   *PageInfo                 `json:"pageInfo,omitempty"`
}

func (ConstraintAnalysisConnection) IsConnection()           {}
func (this ConstraintAnalysisConnection) GetTotalCount() int { return this.TotalCount }
func (this ConstraintAnalysisConnection) GetEdges() []Edge {
	if this.Edges == nil {
		return nil
	}
	interfaceSlice := make([]Edge, 0, len(this.Edges))
	for _, concrete := range this.Edges {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this ConstraintAnalysisConnection) GetPageInfo() *PageInfo { return this.PageInfo }

type ConstraintAnalysisData struct {
	ID   string                    `json:"id"`
	Name string                    `json:"name"`
	From time.Time                 `json:"from"`
	To   *time.Time                `json:"to,omitempty"`
	Data *ConstraintAnalysisResult `json:"data,omitempty"`
}

func (ConstraintAnalysisData) IsNode()            {}
func (this ConstraintAnalysisData) GetID() string { return this.ID }

type ConstraintAnalysisEdge struct {
	Node   *ConstraintAnalysisData `json:"node"`
	Cursor string                  `json:"cursor"`
}

func (ConstraintAnalysisEdge) IsEdge()                {}
func (this ConstraintAnalysisEdge) GetCursor() string { return this.Cursor }
func (this ConstraintAnalysisEdge) GetNode() Node     { return *this.Node }

type ConstraintAnalysisFilter struct {
	Types    []ConstraintAnalysisChangeType `json:"types,omitempty"`
	From     *time.Time                     `json:"from,omitempty"`
	To       *time.Time                     `json:"to,omitempty"`
	NameExpr *string                        `json:"nameExpr,omitempty"`
}

type ConstraintAnalysisInput struct {
	Type       ConstraintAnalysisChangeType `json:"type"`
	LoadChange *LoadChangesInput            `json:"loadChange,omitempty"`
	Name       *string                      `json:"name,omitempty"`
}

type ConstraintAnalysisResult struct {
	Type       ConstraintAnalysisChangeType `json:"type"`
	Config     *ConstraintResource          `json:"config,omitempty"`
	LoadChange *LoadChangesResult           `json:"loadChange,omitempty"`
	Status     string                       `json:"status"`
	AdgEdges   []*ADGEdge                   `json:"adgEdges"`
}

type ConstraintResource struct {
	EntityID          string  `json:"entityId"`
	Entity            *Entity `json:"entity"`
	AttributeName     string  `json:"attributeName"`
	CurrentValue      float64 `json:"currentValue"`
	InitialValue      float64 `json:"initialValue"`
	ResultValue       float64 `json:"resultValue"`
	PercentDifference float64 `json:"percentDifference"`
	Unit              string  `json:"unit"`
}

type ConstraintResourceSummary struct {
	EntityTypeName    string  `json:"entityTypeName"`
	AttributeName     string  `json:"attributeName"`
	CurrentValue      float64 `json:"currentValue"`
	ResultValue       float64 `json:"resultValue"`
	PercentDifference float64 `json:"percentDifference"`
	Unit              string  `json:"unit"`
}

type ContinuousIncreaseIndicatorData struct {
	Name              string             `json:"name"`
	Window            int                `json:"window"`
	Value             *MetricAttribute   `json:"value,omitempty"`
	RelatedAttributes []*MetricAttribute `json:"relatedAttributes,omitempty"`
}

func (ContinuousIncreaseIndicatorData) IsIndicatorData()     {}
func (this ContinuousIncreaseIndicatorData) GetName() string { return this.Name }

type CopilotQueryResponse struct {
	ID         string  `json:"id"`
	Query      string  `json:"query"`
	Response   *string `json:"response,omitempty"`
	CreatedAt  string  `json:"createdAt"`
	FinishedAt *string `json:"finishedAt,omitempty"`
}

type CopilotScope struct {
	Type            CopilotScopeType `json:"type"`
	RelatedEntityID *string          `json:"relatedEntityId,omitempty"`
}

type CopilotScopeInput struct {
	Type            CopilotScopeType `json:"type"`
	RelatedEntityID *string          `json:"relatedEntityId,omitempty"`
}

type CopilotThread struct {
	ID      string                  `json:"id"`
	Scope   *CopilotScope           `json:"scope"`
	Name    *string                 `json:"name,omitempty"`
	Queries []*CopilotQueryResponse `json:"queries,omitempty"`
}

type Defect struct {
	ID                  string         `json:"id"`
	Name                string         `json:"name"`
	EntityID            string         `json:"entityId"`
	Entity              *Entity        `json:"entity"`
	EntityType          string         `json:"entityType"`
	Symptoms            []*Symptom     `json:"symptoms"`
	Slos                []*SloNode     `json:"slos"`
	Events              []*Event       `json:"events"`
	FromTime            string         `json:"fromTime"`
	ToTime              string         `json:"toTime"`
	SLOAtRiskCount      int            `json:"SLOAtRiskCount"`
	Slottl              int            `json:"SLOTTL"`
	ServiceCount        int            `json:"serviceCount"`
	Remediated          bool           `json:"remediated"`
	Likelihood          float64        `json:"likelihood"`
	ActiveCount         int            `json:"activeCount"`
	MissingCount        int            `json:"missingCount"`
	Severity            DefectSeverity `json:"severity"`
	RelatedOccurrrences []*Defect      `json:"relatedOccurrrences"`
	Impacts             []*Symptom     `json:"impacts"`
}

func (Defect) IsNode()            {}
func (this Defect) GetID() string { return this.ID }

type DefectConnection struct {
	TotalCount int           `json:"totalCount"`
	Edges      []*DefectEdge `json:"edges"`
	PageInfo   *PageInfo     `json:"pageInfo,omitempty"`
}

func (DefectConnection) IsConnection()           {}
func (this DefectConnection) GetTotalCount() int { return this.TotalCount }
func (this DefectConnection) GetEdges() []Edge {
	if this.Edges == nil {
		return nil
	}
	interfaceSlice := make([]Edge, 0, len(this.Edges))
	for _, concrete := range this.Edges {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this DefectConnection) GetPageInfo() *PageInfo { return this.PageInfo }

type DefectCount struct {
	EntityType        *string         `json:"entityType,omitempty"`
	DefectName        *string         `json:"defectName,omitempty"`
	Severity          *DefectSeverity `json:"severity,omitempty"`
	Time              *string         `json:"time,omitempty"`
	DefectCount       int             `json:"defectCount"`
	DefectManualCount int             `json:"defectManualCount"`
	DefectAutoCount   int             `json:"defectAutoCount"`
}

type DefectDef struct {
	Name              string             `json:"name"`
	Description       *DefectDescription `json:"description"`
	EntityTypeName    string             `json:"entityTypeName"`
	EntityType        *EntityTypeDef     `json:"entityType"`
	Symptoms          []*SymptomDef      `json:"symptoms"`
	Events            []*EventDef        `json:"events"`
	ContextAttributes []string           `json:"contextAttributes,omitempty"`
}

type DefectDescription struct {
	Summary            string               `json:"summary"`
	Details            *string              `json:"details,omitempty"`
	RemediationOptions []*RemediationOption `json:"remediationOptions"`
}

type DefectEdge struct {
	Node   *Defect `json:"node"`
	Cursor string  `json:"cursor"`
}

func (DefectEdge) IsEdge()                {}
func (this DefectEdge) GetCursor() string { return this.Cursor }
func (this DefectEdge) GetNode() Node     { return *this.Node }

type DefectFilter struct {
	IncludeNonSvcImpact   *bool              `json:"includeNonSvcImpact,omitempty"`
	IncludeInactiveDefect *bool              `json:"includeInactiveDefect,omitempty"`
	Severities            []DefectSeverity   `json:"severities,omitempty"`
	State                 *DefectState       `json:"state,omitempty"`
	DefectNames           []string           `json:"defectNames,omitempty"`
	EntityTypes           []string           `json:"entityTypes,omitempty"`
	StartTime             *time.Time         `json:"startTime,omitempty"`
	EndTime               *time.Time         `json:"endTime,omitempty"`
	EntityName            *string            `json:"entityName,omitempty"`
	ScopesFilter          *ScopesFilterInput `json:"scopesFilter,omitempty"`
}

type DefectStat struct {
	EntityType *string `json:"entityType,omitempty"`
	DefectName *string `json:"defectName,omitempty"`
	Mttr       int     `json:"mttr"`
}

type DurationIndicatorData struct {
	Name              string             `json:"name"`
	Window            int                `json:"window"`
	Le                float64            `json:"le"`
	Quantile          float64            `json:"quantile"`
	Threshold         *MetricAttribute   `json:"threshold,omitempty"`
	Value             *MetricAttribute   `json:"value,omitempty"`
	RelatedAttributes []*MetricAttribute `json:"relatedAttributes,omitempty"`
}

func (DurationIndicatorData) IsIndicatorData()     {}
func (this DurationIndicatorData) GetName() string { return this.Name }

type Entity struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	TypeName string     `json:"typeName"`
	Symptoms []*Symptom `json:"symptoms"`
	Events   []*Event   `json:"events"`
	Labels   []*Label   `json:"labels"`
	Slos     []*Slo     `json:"slos"`
	Defects  []*Defect  `json:"defects"`
	Severity string     `json:"severity"`
}

func (Entity) IsNode()            {}
func (this Entity) GetID() string { return this.ID }

type EntityAttributeQuery struct {
	ID         string   `json:"id"`
	Attributes []string `json:"attributes"`
}

type EntityAttributeQueryResult struct {
	ID         string      `json:"id"`
	Attributes []Attribute `json:"attributes"`
}

type EntityConnection struct {
	TotalCount int           `json:"totalCount"`
	Edges      []*EntityEdge `json:"edges"`
	PageInfo   *PageInfo     `json:"pageInfo,omitempty"`
}

func (EntityConnection) IsConnection()           {}
func (this EntityConnection) GetTotalCount() int { return this.TotalCount }
func (this EntityConnection) GetEdges() []Edge {
	if this.Edges == nil {
		return nil
	}
	interfaceSlice := make([]Edge, 0, len(this.Edges))
	for _, concrete := range this.Edges {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this EntityConnection) GetPageInfo() *PageInfo { return this.PageInfo }

type EntityData struct {
	ID         string          `json:"id"`
	Attributes []Attribute     `json:"attributes"`
	Indicators []IndicatorData `json:"indicators"`
	Resources  []ResourceData  `json:"resources"`
}

type EntityDataQuery struct {
	ID         string   `json:"id"`
	Attributes []string `json:"attributes,omitempty"`
	Resources  []string `json:"resources,omitempty"`
	Indicators []string `json:"indicators,omitempty"`
}

type EntityDataQueryResult struct {
	Entities []*EntityData `json:"entities"`
}

type EntityEdge struct {
	Node   *Entity `json:"node"`
	Cursor string  `json:"cursor"`
}

func (EntityEdge) IsEdge()                {}
func (this EntityEdge) GetCursor() string { return this.Cursor }
func (this EntityEdge) GetNode() Node     { return *this.Node }

type EntityFilter struct {
	NameExpr            *string            `json:"nameExpr,omitempty"`
	EntityTypes         []string           `json:"entityTypes,omitempty"`
	Severities          []string           `json:"severities,omitempty"`
	IncludeDerivedTypes *bool              `json:"includeDerivedTypes,omitempty"`
	ScopesFilter        *ScopesFilterInput `json:"scopesFilter,omitempty"`
}

type EntityQuery struct {
	Start       *time.Time         `json:"start,omitempty"`
	End         *time.Time         `json:"end,omitempty"`
	StepMinutes *int               `json:"stepMinutes,omitempty"`
	Entities    []*EntityDataQuery `json:"entities"`
}

type EntityRelatedDefects struct {
	Entity         *Entity         `json:"entity"`
	RelatedDefects *RelatedDefects `json:"relatedDefects"`
}

type EntityRelation struct {
	Name     string    `json:"name"`
	Entities []*Entity `json:"entities"`
}

type EntityRelationCount struct {
	Name     string  `json:"name"`
	TypeName *string `json:"typeName,omitempty"`
	Count    *int    `json:"count,omitempty"`
}

type EntityTypeCount struct {
	EntityType string  `json:"entityType"`
	Severity   *string `json:"severity,omitempty"`
	Count      int     `json:"count"`
}

type EntityTypeDef struct {
	Name              string          `json:"name"`
	Defects           []*DefectDef    `json:"defects"`
	Attributes        []*AttributeDef `json:"attributes"`
	Symptoms          []*SymptomDef   `json:"symptoms"`
	Events            []*EventDef     `json:"events"`
	Relations         []*RelationDef  `json:"relations"`
	Resources         []*ResourceDef  `json:"resources"`
	Indicators        []*IndicatorDef `json:"indicators"`
	ContextAttributes []string        `json:"contextAttributes,omitempty"`
}

type EntityTypeDefFilter struct {
	EntityTypes         []string `json:"EntityTypes,omitempty"`
	IncludeDerivedTypes *bool    `json:"includeDerivedTypes,omitempty"`
}

type Event struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	EntityID      string    `json:"entityId"`
	Entity        *Entity   `json:"entity"`
	EntityType    string    `json:"entityType"`
	Time          string    `json:"time"`
	Active        bool      `json:"active"`
	ActiveDefects []*Defect `json:"activeDefects,omitempty"`
}

type EventDef struct {
	Name           string         `json:"name"`
	EntityTypeName string         `json:"entityTypeName"`
	EntityType     *EntityTypeDef `json:"entityType"`
	Impacts        []*Slo         `json:"impacts"`
}

type Feedback struct {
	Type              FeedbackType       `json:"type"`
	RelatedObjectType FeedbackObjectType `json:"relatedObjectType"`
	RelatedObjectID   string             `json:"relatedObjectId"`
	Message           string             `json:"message"`
}

type FloatAttribute struct {
	Name     string        `json:"name"`
	AttrType AttributeType `json:"attrType"`
	Value    float64       `json:"value"`
	Unit     string        `json:"unit"`
}

func (FloatAttribute) IsAttribute()                    {}
func (this FloatAttribute) GetName() string            { return this.Name }
func (this FloatAttribute) GetAttrType() AttributeType { return this.AttrType }
func (this FloatAttribute) GetUnit() string            { return this.Unit }

type HistogramAttribute struct {
	Name     string        `json:"name"`
	AttrType AttributeType `json:"attrType"`
	Count    *Metric       `json:"count"`
	Sum      *Metric       `json:"sum"`
	Buckets  []*Bucket     `json:"buckets"`
	Unit     string        `json:"unit"`
}

func (HistogramAttribute) IsAttribute()                    {}
func (this HistogramAttribute) GetName() string            { return this.Name }
func (this HistogramAttribute) GetAttrType() AttributeType { return this.AttrType }
func (this HistogramAttribute) GetUnit() string            { return this.Unit }

type IndicatorDef struct {
	Name              string          `json:"name"`
	Type              string          `json:"type"`
	Description       *string         `json:"description,omitempty"`
	Attributes        []*AttributeDef `json:"attributes"`
	Symptoms          []*SymptomDef   `json:"symptoms"`
	ContextAttributes []string        `json:"contextAttributes,omitempty"`
}

type IntAttribute struct {
	Name     string        `json:"name"`
	AttrType AttributeType `json:"attrType"`
	Value    int           `json:"value"`
	Unit     string        `json:"unit"`
}

func (IntAttribute) IsAttribute()                    {}
func (this IntAttribute) GetName() string            { return this.Name }
func (this IntAttribute) GetAttrType() AttributeType { return this.AttrType }
func (this IntAttribute) GetUnit() string            { return this.Unit }

type Label struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type LoadChangesEntityInput struct {
	EntityID      string   `json:"entityId"`
	ResourceName  string   `json:"resourceName"`
	ChangePercent *float64 `json:"changePercent,omitempty"`
	AbsoluteValue *float64 `json:"absoluteValue,omitempty"`
}

type LoadChangesInput struct {
	Entities []*LoadChangesEntityInput `json:"entities"`
}

type LoadChangesResult struct {
	Resources       []*ConstraintResource        `json:"resources"`
	ResourceSummary []*ConstraintResourceSummary `json:"resourceSummary"`
}

type Manifestation struct {
	ID      string   `json:"id"`
	Symptom *Symptom `json:"symptom,omitempty"`
	Event   *Event   `json:"event,omitempty"`
	Slo     *Slo     `json:"slo,omitempty"`
}

func (Manifestation) IsNode()            {}
func (this Manifestation) GetID() string { return this.ID }

type ManifestationConnection struct {
	TotalCount int                  `json:"totalCount"`
	Edges      []*ManifestationEdge `json:"edges"`
	PageInfo   *PageInfo            `json:"pageInfo,omitempty"`
}

func (ManifestationConnection) IsConnection()           {}
func (this ManifestationConnection) GetTotalCount() int { return this.TotalCount }
func (this ManifestationConnection) GetEdges() []Edge {
	if this.Edges == nil {
		return nil
	}
	interfaceSlice := make([]Edge, 0, len(this.Edges))
	for _, concrete := range this.Edges {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this ManifestationConnection) GetPageInfo() *PageInfo { return this.PageInfo }

type ManifestationCount struct {
	EntityType         *string            `json:"entityType,omitempty"`
	ManifestationName  *string            `json:"manifestationName,omitempty"`
	Time               *string            `json:"time,omitempty"`
	ManifestationCount int                `json:"manifestationCount"`
	ManifestationType  *ManifestationType `json:"manifestationType,omitempty"`
}

type ManifestationEdge struct {
	Node   *Manifestation `json:"node"`
	Cursor string         `json:"cursor"`
}

func (ManifestationEdge) IsEdge()                {}
func (this ManifestationEdge) GetCursor() string { return this.Cursor }
func (this ManifestationEdge) GetNode() Node     { return *this.Node }

type ManifestationFilter struct {
	ManifestationNames []string            `json:"manifestationNames,omitempty"`
	EntityTypes        []string            `json:"entityTypes,omitempty"`
	StartTime          *time.Time          `json:"startTime,omitempty"`
	EndTime            *time.Time          `json:"endTime,omitempty"`
	EntityName         *string             `json:"entityName,omitempty"`
	ManifestationTypes []ManifestationType `json:"manifestationTypes,omitempty"`
	ScopesFilter       *ScopesFilterInput  `json:"scopesFilter,omitempty"`
}

type Metric struct {
	Values []*SamplePair `json:"values"`
}

type MetricAttribute struct {
	Name     string        `json:"name"`
	AttrType AttributeType `json:"attrType"`
	Value    *Metric       `json:"value"`
	Unit     string        `json:"unit"`
}

func (MetricAttribute) IsAttribute()                    {}
func (this MetricAttribute) GetName() string            { return this.Name }
func (this MetricAttribute) GetAttrType() AttributeType { return this.AttrType }
func (this MetricAttribute) GetUnit() string            { return this.Unit }

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool   `json:"hasNextPage"`
	HasPreviousPage bool   `json:"hasPreviousPage"`
	StartCursor     string `json:"startCursor"`
	EndCursor       string `json:"endCursor"`
	TotalCount      *int   `json:"totalCount,omitempty"`
}

type Query struct {
}

type RatioIndicatorData struct {
	Name              string             `json:"name"`
	Window            int                `json:"window"`
	Threshold         *MetricAttribute   `json:"threshold,omitempty"`
	Count             *MetricAttribute   `json:"count,omitempty"`
	Ratio             *MetricAttribute   `json:"ratio,omitempty"`
	Total             *MetricAttribute   `json:"total,omitempty"`
	RelatedAttributes []*MetricAttribute `json:"relatedAttributes,omitempty"`
}

func (RatioIndicatorData) IsIndicatorData()     {}
func (this RatioIndicatorData) GetName() string { return this.Name }

type RelatedByFilter struct {
	RelatedIds   []string           `json:"relatedIds,omitempty"`
	ScopesFilter *ScopesFilterInput `json:"scopesFilter,omitempty"`
}

type RelatedDefects struct {
	ImpactingDefects   []*Defect `json:"impactingDefects"`
	AggregatingDefects []*Defect `json:"aggregatingDefects"`
}

type RelatedEntityCount struct {
	ID            string                 `json:"id"`
	Entity        *Entity                `json:"entity"`
	RelatedCounts []*EntityRelationCount `json:"relatedCounts"`
}

func (RelatedEntityCount) IsNode()            {}
func (this RelatedEntityCount) GetID() string { return this.ID }

type RelatedEntityCountConnection struct {
	TotalCount int                       `json:"totalCount"`
	Edges      []*RelatedEntityCountEdge `json:"edges"`
	PageInfo   *PageInfo                 `json:"pageInfo,omitempty"`
}

func (RelatedEntityCountConnection) IsConnection()           {}
func (this RelatedEntityCountConnection) GetTotalCount() int { return this.TotalCount }
func (this RelatedEntityCountConnection) GetEdges() []Edge {
	if this.Edges == nil {
		return nil
	}
	interfaceSlice := make([]Edge, 0, len(this.Edges))
	for _, concrete := range this.Edges {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this RelatedEntityCountConnection) GetPageInfo() *PageInfo { return this.PageInfo }

type RelatedEntityCountEdge struct {
	Node   *RelatedEntityCount `json:"node"`
	Cursor string              `json:"cursor"`
}

func (RelatedEntityCountEdge) IsEdge()                {}
func (this RelatedEntityCountEdge) GetCursor() string { return this.Cursor }
func (this RelatedEntityCountEdge) GetNode() Node     { return *this.Node }

type RelationDef struct {
	Name string `json:"name"`
}

type RemediationOption struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

type ResourceDef struct {
	Name       string          `json:"name"`
	Type       string          `json:"type"`
	Defects    []*DefectDef    `json:"defects"`
	Attributes []*AttributeDef `json:"attributes"`
	Symptoms   []*SymptomDef   `json:"symptoms"`
}

type Slo struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	EntityID   string  `json:"entityId"`
	Entity     *Entity `json:"entity"`
	EntityType string  `json:"entityType"`
	Active     bool    `json:"active"`
	FromTime   string  `json:"fromTime"`
}

type SLOHealth struct {
	EntityType *string `json:"entityType,omitempty"`
	SloName    *string `json:"sloName,omitempty"`
	Time       *string `json:"time,omitempty"`
	SloHealth  int     `json:"sloHealth"`
}

type SamplePair struct {
	Timestamp time.Time `json:"timestamp"`
	Value     float64   `json:"value"`
}

type Scope struct {
	TypeName   string   `json:"typeName"`
	TypeValues []string `json:"typeValues"`
	Exclude    *bool    `json:"exclude,omitempty"`
}

type ScopeInput struct {
	TypeName   string   `json:"typeName"`
	TypeValues []string `json:"typeValues"`
	NameExpr   *string  `json:"nameExpr,omitempty"`
	Exclude    *bool    `json:"exclude,omitempty"`
}

type ScopesFilter struct {
	Scopes []*Scope `json:"scopes"`
}

type ScopesFilterInput struct {
	Scopes []*ScopeInput `json:"scopes"`
}

type SloConnection struct {
	TotalCount int        `json:"totalCount"`
	Edges      []*SloEdge `json:"edges"`
	PageInfo   *PageInfo  `json:"pageInfo,omitempty"`
}

func (SloConnection) IsConnection()           {}
func (this SloConnection) GetTotalCount() int { return this.TotalCount }
func (this SloConnection) GetEdges() []Edge {
	if this.Edges == nil {
		return nil
	}
	interfaceSlice := make([]Edge, 0, len(this.Edges))
	for _, concrete := range this.Edges {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this SloConnection) GetPageInfo() *PageInfo { return this.PageInfo }

type SloCount struct {
	EntityType string  `json:"entityType"`
	Severity   *string `json:"severity,omitempty"`
	Count      int     `json:"count"`
}

type SloDataQuery struct {
	Start       *time.Time  `json:"start,omitempty"`
	End         *time.Time  `json:"end,omitempty"`
	StepMinutes *int        `json:"stepMinutes,omitempty"`
	Queries     []*SloQuery `json:"queries,omitempty"`
}

type SloEdge struct {
	Node   *SloNode `json:"node"`
	Cursor string   `json:"cursor"`
}

func (SloEdge) IsEdge()                {}
func (this SloEdge) GetCursor() string { return this.Cursor }
func (this SloEdge) GetNode() Node     { return *this.Node }

type SloFilter struct {
	EntityTypes     []string         `json:"entityTypes,omitempty"`
	States          []SloState       `json:"states,omitempty"`
	NameExpr        *string          `json:"nameExpr,omitempty"`
	MetricQuery     *SloDataQuery    `json:"metricQuery,omitempty"`
	RelatedByFilter *RelatedByFilter `json:"relatedByFilter,omitempty"`
}

type SloNode struct {
	ID            string      `json:"id"`
	Entity        *Entity     `json:"entity"`
	RelatedEntity *Entity     `json:"relatedEntity,omitempty"`
	Metrics       *EntityData `json:"metrics,omitempty"`
	State         *SloState   `json:"state,omitempty"`
}

func (SloNode) IsNode()            {}
func (this SloNode) GetID() string { return this.ID }

type SloQuery struct {
	SloType    string   `json:"sloType"`
	Attributes []string `json:"attributes,omitempty"`
	Resources  []string `json:"resources,omitempty"`
	Indicators []string `json:"indicators,omitempty"`
}

type StringAttribute struct {
	Name     string        `json:"name"`
	AttrType AttributeType `json:"attrType"`
	Value    string        `json:"value"`
	Unit     string        `json:"unit"`
}

func (StringAttribute) IsAttribute()                    {}
func (this StringAttribute) GetName() string            { return this.Name }
func (this StringAttribute) GetAttrType() AttributeType { return this.AttrType }
func (this StringAttribute) GetUnit() string            { return this.Unit }

type Symptom struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	EntityID      string             `json:"entityId"`
	Entity        *Entity            `json:"entity"`
	EntityType    string             `json:"entityType"`
	Active        bool               `json:"active"`
	State         ManifestationState `json:"state"`
	IsPropagated  bool               `json:"isPropagated"`
	FromTime      string             `json:"fromTime"`
	ToTime        string             `json:"toTime"`
	ActiveDefects []*Defect          `json:"activeDefects,omitempty"`
}

type SymptomDef struct {
	Name              string         `json:"name"`
	EntityTypeName    string         `json:"entityTypeName"`
	EntityType        *EntityTypeDef `json:"entityType"`
	Impacts           []*Slo         `json:"impacts"`
	ContextAttributes []string       `json:"contextAttributes,omitempty"`
}

type TableAttribute struct {
	Name     string         `json:"name"`
	AttrType AttributeType  `json:"attrType"`
	Unit     string         `json:"unit"`
	Columns  []*TableColumn `json:"columns"`
	Rows     []*TableRow    `json:"rows"`
}

func (TableAttribute) IsAttribute()                    {}
func (this TableAttribute) GetName() string            { return this.Name }
func (this TableAttribute) GetAttrType() AttributeType { return this.AttrType }
func (this TableAttribute) GetUnit() string            { return this.Unit }

type TableCell struct {
	IntValue    *int     `json:"intValue,omitempty"`
	FloatValue  *float64 `json:"floatValue,omitempty"`
	BoolValue   *bool    `json:"boolValue,omitempty"`
	StringValue *string  `json:"stringValue,omitempty"`
}

type TableColumn struct {
	Name        string        `json:"name"`
	ColumnType  AttributeType `json:"columnType"`
	ContentType *string       `json:"contentType,omitempty"`
}

type TableRow struct {
	Values []*TableCell `json:"values"`
}

type ThresholdIndicatorData struct {
	Name              string             `json:"name"`
	Window            int                `json:"window"`
	Threshold         *MetricAttribute   `json:"threshold,omitempty"`
	Value             *MetricAttribute   `json:"value,omitempty"`
	RelatedAttributes []*MetricAttribute `json:"relatedAttributes,omitempty"`
}

func (ThresholdIndicatorData) IsIndicatorData()     {}
func (this ThresholdIndicatorData) GetName() string { return this.Name }

type TopologyEdge struct {
	FromEntity *Entity `json:"fromEntity"`
	ToEntity   *Entity `json:"toEntity"`
	EdgeType   string  `json:"edgeType"`
}

type USEResourceData struct {
	Name        string        `json:"name"`
	Utilization IndicatorData `json:"utilization"`
	Saturation  IndicatorData `json:"saturation"`
	Errors      IndicatorData `json:"errors"`
}

func (USEResourceData) IsResourceData()      {}
func (this USEResourceData) GetName() string { return this.Name }

type UserSetting struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	TenantID string `json:"tenantId"`
	Value    string `json:"value"`
}

type UserSettingInput struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	TenantID string `json:"tenantId"`
	Value    string `json:"value"`
}

type UserSettings struct {
	ID       string         `json:"id"`
	Settings []*UserSetting `json:"settings"`
}

type UserSettingsFilter struct {
	Name     *string `json:"name,omitempty"`
	Type     *string `json:"type,omitempty"`
	TenantID *string `json:"tenantId,omitempty"`
}

type UserSettingsInput struct {
	ID       string              `json:"id"`
	Settings []*UserSettingInput `json:"settings"`
}

type UtilizationIndicatorData struct {
	Name              string             `json:"name"`
	Window            int                `json:"window"`
	Usage             *MetricAttribute   `json:"usage,omitempty"`
	Capacity          *MetricAttribute   `json:"capacity,omitempty"`
	Threshold         *MetricAttribute   `json:"threshold,omitempty"`
	Utilization       *MetricAttribute   `json:"utilization,omitempty"`
	RelatedAttributes []*MetricAttribute `json:"relatedAttributes,omitempty"`
}

func (UtilizationIndicatorData) IsIndicatorData()     {}
func (this UtilizationIndicatorData) GetName() string { return this.Name }

type VersionInfo struct {
	MediationVersion string `json:"mediationVersion"`
}

type WorkloadCount struct {
	EntityType *string `json:"entityType,omitempty"`
	Count      int     `json:"count"`
	Time       string  `json:"time"`
}

type AttributeType string

const (
	AttributeTypeString  AttributeType = "STRING"
	AttributeTypeBoolean AttributeType = "BOOLEAN"
	AttributeTypeInt     AttributeType = "INT"
	AttributeTypeFloat   AttributeType = "FLOAT"
)

var AllAttributeType = []AttributeType{
	AttributeTypeString,
	AttributeTypeBoolean,
	AttributeTypeInt,
	AttributeTypeFloat,
}

func (e AttributeType) IsValid() bool {
	switch e {
	case AttributeTypeString, AttributeTypeBoolean, AttributeTypeInt, AttributeTypeFloat:
		return true
	}
	return false
}

func (e AttributeType) String() string {
	return string(e)
}

func (e *AttributeType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AttributeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AttributeType", str)
	}
	return nil
}

func (e AttributeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ConstraintAnalysisChangeType string

const (
	ConstraintAnalysisChangeTypeLoadChange  ConstraintAnalysisChangeType = "LOAD_CHANGE"
	ConstraintAnalysisChangeTypeCurrentLoad ConstraintAnalysisChangeType = "CURRENT_LOAD"
)

var AllConstraintAnalysisChangeType = []ConstraintAnalysisChangeType{
	ConstraintAnalysisChangeTypeLoadChange,
	ConstraintAnalysisChangeTypeCurrentLoad,
}

func (e ConstraintAnalysisChangeType) IsValid() bool {
	switch e {
	case ConstraintAnalysisChangeTypeLoadChange, ConstraintAnalysisChangeTypeCurrentLoad:
		return true
	}
	return false
}

func (e ConstraintAnalysisChangeType) String() string {
	return string(e)
}

func (e *ConstraintAnalysisChangeType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConstraintAnalysisChangeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConstraintAnalysisChangeType", str)
	}
	return nil
}

func (e ConstraintAnalysisChangeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type CopilotScopeType string

const (
	CopilotScopeTypeTopology CopilotScopeType = "Topology"
	CopilotScopeTypeService  CopilotScopeType = "Service"
)

var AllCopilotScopeType = []CopilotScopeType{
	CopilotScopeTypeTopology,
	CopilotScopeTypeService,
}

func (e CopilotScopeType) IsValid() bool {
	switch e {
	case CopilotScopeTypeTopology, CopilotScopeTypeService:
		return true
	}
	return false
}

func (e CopilotScopeType) String() string {
	return string(e)
}

func (e *CopilotScopeType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CopilotScopeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CopilotScopeType", str)
	}
	return nil
}

func (e CopilotScopeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type DefectSeverity string

const (
	DefectSeverityLow      DefectSeverity = "Low"
	DefectSeverityMedium   DefectSeverity = "Medium"
	DefectSeverityHigh     DefectSeverity = "High"
	DefectSeverityCritical DefectSeverity = "Critical"
)

var AllDefectSeverity = []DefectSeverity{
	DefectSeverityLow,
	DefectSeverityMedium,
	DefectSeverityHigh,
	DefectSeverityCritical,
}

func (e DefectSeverity) IsValid() bool {
	switch e {
	case DefectSeverityLow, DefectSeverityMedium, DefectSeverityHigh, DefectSeverityCritical:
		return true
	}
	return false
}

func (e DefectSeverity) String() string {
	return string(e)
}

func (e *DefectSeverity) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DefectSeverity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DefectSeverity", str)
	}
	return nil
}

func (e DefectSeverity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type DefectState string

const (
	DefectStateInactive DefectState = "INACTIVE"
	DefectStateActive   DefectState = "ACTIVE"
	DefectStateAll      DefectState = "ALL"
)

var AllDefectState = []DefectState{
	DefectStateInactive,
	DefectStateActive,
	DefectStateAll,
}

func (e DefectState) IsValid() bool {
	switch e {
	case DefectStateInactive, DefectStateActive, DefectStateAll:
		return true
	}
	return false
}

func (e DefectState) String() string {
	return string(e)
}

func (e *DefectState) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DefectState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DefectState", str)
	}
	return nil
}

func (e DefectState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type FeedbackObjectType string

const (
	FeedbackObjectTypeCopilotQuery FeedbackObjectType = "CopilotQuery"
)

var AllFeedbackObjectType = []FeedbackObjectType{
	FeedbackObjectTypeCopilotQuery,
}

func (e FeedbackObjectType) IsValid() bool {
	switch e {
	case FeedbackObjectTypeCopilotQuery:
		return true
	}
	return false
}

func (e FeedbackObjectType) String() string {
	return string(e)
}

func (e *FeedbackObjectType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FeedbackObjectType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FeedbackObjectType", str)
	}
	return nil
}

func (e FeedbackObjectType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type FeedbackType string

const (
	FeedbackTypePositive FeedbackType = "Positive"
	FeedbackTypeNegative FeedbackType = "Negative"
)

var AllFeedbackType = []FeedbackType{
	FeedbackTypePositive,
	FeedbackTypeNegative,
}

func (e FeedbackType) IsValid() bool {
	switch e {
	case FeedbackTypePositive, FeedbackTypeNegative:
		return true
	}
	return false
}

func (e FeedbackType) String() string {
	return string(e)
}

func (e *FeedbackType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FeedbackType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FeedbackType", str)
	}
	return nil
}

func (e FeedbackType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ManifestationState string

const (
	ManifestationStateUnknown  ManifestationState = "UNKNOWN"
	ManifestationStateActive   ManifestationState = "ACTIVE"
	ManifestationStateInactive ManifestationState = "INACTIVE"
)

var AllManifestationState = []ManifestationState{
	ManifestationStateUnknown,
	ManifestationStateActive,
	ManifestationStateInactive,
}

func (e ManifestationState) IsValid() bool {
	switch e {
	case ManifestationStateUnknown, ManifestationStateActive, ManifestationStateInactive:
		return true
	}
	return false
}

func (e ManifestationState) String() string {
	return string(e)
}

func (e *ManifestationState) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ManifestationState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ManifestationState", str)
	}
	return nil
}

func (e ManifestationState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ManifestationType string

const (
	ManifestationTypeSymptom ManifestationType = "Symptom"
	ManifestationTypeEvent   ManifestationType = "Event"
	ManifestationTypeSlo     ManifestationType = "Slo"
)

var AllManifestationType = []ManifestationType{
	ManifestationTypeSymptom,
	ManifestationTypeEvent,
	ManifestationTypeSlo,
}

func (e ManifestationType) IsValid() bool {
	switch e {
	case ManifestationTypeSymptom, ManifestationTypeEvent, ManifestationTypeSlo:
		return true
	}
	return false
}

func (e ManifestationType) String() string {
	return string(e)
}

func (e *ManifestationType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ManifestationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ManifestationType", str)
	}
	return nil
}

func (e ManifestationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SloState string

const (
	SloStateNormal   SloState = "NORMAL"
	SloStateAtRisk   SloState = "AT_RISK"
	SloStateViolated SloState = "VIOLATED"
)

var AllSloState = []SloState{
	SloStateNormal,
	SloStateAtRisk,
	SloStateViolated,
}

func (e SloState) IsValid() bool {
	switch e {
	case SloStateNormal, SloStateAtRisk, SloStateViolated:
		return true
	}
	return false
}

func (e SloState) String() string {
	return string(e)
}

func (e *SloState) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SloState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SloState", str)
	}
	return nil
}

func (e SloState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
